#!/bin/sh

while [ $# -gt 0 ]
do
  case "$1" in
    -path )
      shift
      ;;
    -* )
      exec >&2
      echo "$0: Unrecognized option $1"
      exit 1
      ;;
    * )
      break
      ;;
  esac
done

if [ "$#" -gt 0 ]
then
  target="$1"
  MASTER=$(cd "$target" && pwd)
else
  if [ -z "${EDIRECT_PUBMED_MASTER}" ]
  then
    echo "Must supply path to master archive area or set EDIRECT_PUBMED_MASTER environment variable"
    exit 1
  else
    MASTER="${EDIRECT_PUBMED_MASTER}"
    MASTER=${MASTER%/}
  fi
fi

for dir in Archive Cleaned Indexed Inverted Merged Postings Pubmed
do
  mkdir -p "$MASTER/$dir"
done

if [ ! -f "$MASTER/Archive/CACHEDIR.TAG" ]
then
  pm-prepare "$MASTER/Archive"
fi

echo "Downloading PubMed Files"
cd "$MASTER/Pubmed"
download-pubmed baseline updatefiles
echo ""

echo "Cleaning PubMed Archive"
pm-clean "$MASTER/Cleaned"
echo ""

echo "Populating PubMed Archive"
cd "$MASTER/Cleaned"
pm-stash "$MASTER/Archive"
echo ""

echo "Refreshing Versioned Records"
pm-refresh "$MASTER/Archive"
echo ""

echo "End of PubMed Update"
