#!/bin/sh

# Usage: ftp-ls SERVER PATH

mydir=`dirname "$0"`
addr=`"$mydir"/eaddress`

list_file_names()
{
ftp -n -V -i "$1" <<EOF
user anonymous "$addr"
cd "$2"
ls *
exit
EOF
}

list_file_names "$@" | sed -ne 's,^-.*[ 	],,p; s,^d.*[ 	]\(.*\),\1/,p'
