#!/usr/bin/env perl
# Usage: ftp-ls SERVER PATH

use strict;
use warnings;

use Net::FTP;

my $server = shift;
my $dir    = shift;
my $ftp    = new Net::FTP($server, Passive => 1)
  or die "Unable to connect to FTP server: $!";

$ftp->login or die "Unable to log in to FTP server";
$ftp->cwd($dir) or die "Unable to change to $dir";
my $contents = $ftp->dir;
die "Unable to list contents" unless defined $contents;

for (@$contents) {
    if (/^-.*?(\S*)$/) {
        print "$1\n";
    } elsif (/^d.*?(\S*)$/) {
        print "$1/\n";
    } elsif (/^l.*?(\S*) -> \S*$/) {
        print "$1@\n";
    }
}
