#!/bin/sh

target=""
flag="none"
mode="query"

while [ $# -gt 0 ]
do
  case "$1" in
    -h | -help | --help )
      mode=help
      break
      ;;
    -path | -master )
      target=$2
      shift
      shift
      ;;
    -stem | -stems )
      flag="stems"
      shift
      ;;
    -count )
      mode="count"
      shift
      ;;
    -counts )
      mode="counts"
      shift
      ;;
    -query )
      mode="query"
      shift
      ;;
    -phrase )
      mode="phrase"
      shift
      ;;
    -* )
      exec >&2
      echo "$0: Unrecognized option $1"
      exit 1
      ;;
    * )
      break
      ;;
  esac
done

if [ $mode = "help" ]
then
  cat <<EOF
USAGE: $0
       [-path path_to_pubmed_master]
       [-stems]
       -count | -counts | -phrase | [-query]
       query arguments

EXAMPLE: local-phrase-search catabolite repress* AND protease inhibit*
EOF
  exit
fi

if [ -z "$target" ]
then
  if [ -z "${EDIRECT_PUBMED_MASTER}" ]
  then
    echo "Must supply -path argument to master archive area or set EDIRECT_PUBMED_MASTER environment variable"
    exit 1
  else
    MASTER="${EDIRECT_PUBMED_MASTER}"
    target="$MASTER"
  fi
else
  argument="$target"
  target=$(cd "$argument" && pwd)
fi

osname=`uname -s | sed -e 's/_NT-.*$/_NT/; s/^MINGW[0-9]*/CYGWIN/'`
if [ "$osname" = "CYGWIN_NT" -a -x /bin/cygpath ]
then
  target=`cygpath -w "$target"`
fi

target=${target%/}

case "$mode" in
   count )
     rchive -flag "$flag" -count "$target/Postings" "$*" 
     ;;
   counts )
     rchive -flag "$flag" -counts "$target/Postings" "$*" 
     ;;
   query )
     rchive -flag "$flag" -query "$target/Postings" "$*"
     ;;
   phrase )
     rchive -flag "$flag" -query "$target/Postings" "$*" |
     rchive -fetch "$target/Archive" -head "<PubmedArticleSet>" -tail "</PubmedArticleSet>" |
     xtract -head "<PubmedArticleSet>" -tail "</PubmedArticleSet>" -pattern PubmedArticle -phrase "$*"
     ;;
esac
