#!/bin/sh

if [ "$#" -eq 0 ]
then
  echo "Must supply path for cleaned files"
  exit 1
fi

target="$1"

target=${target%/}

for fl in *.xml.gz
do
  base=${fl%.xml.gz}
  if [ -f "$target/$base.xml.gz" ]
  then
    continue
  fi
  echo "$base"
  gunzip -c "$fl" |
  xtract -mixed -compress -format flush |
  gzip > "$target/$base.xml.gz"
done
