#!/bin/sh

if [ "$#" -eq 0 ]
then
  echo "Must supply path for inverted files"
  exit 1
fi

target="$1"

target=${target%/}

for fld in NORM PAIR STEM GRFT
do
  rm -f "$target/$fld/versioned.inv.gz"
done

for fld in NORM PAIR STEM GRFT
do
  mkdir -p "$target/$fld"
  recent=$(ls -r "$target"/$fld/*.inv.gz 2>/dev/null | head -n 1)
  if [ -s "$recent" ]
  then
    rm "$recent"
  fi
done

n=1
for fl in *.e2x.gz
do
  if [ "$fl" = "versioned.e2x.gz" ]
  then
    continue
  fi
  echo "$fl"
done |
xargs -n 20 echo |
while read files
do
  outfile=$(printf pubmed%02d.inv.gz $n)
  n=$((n+1))
  for fld in NORM PAIR STEM GRFT
  do
    if [ -f "$target/$fld/$outfile" ]
    then
      continue
    fi
    echo "$outfile $fld"
    rchive -invert "$fld" $files | gzip -1 > "$target/$fld/$outfile"
    sleep 2
  done
done

if [ -f "versioned.e2x.gz" ]
then
  for fld in NORM PAIR STEM GRFT
  do
    if [ -f "$target/$fld/versioned.inv.gz" ]
    then
      continue
    fi
    echo "versioned"
    rchive -invert "$fld" "versioned.e2x.gz" | gzip -1 > "$target/$fld/versioned.inv.gz"
  done
fi
