#!/bin/sh

if [ "$#" -eq 0 ]
then
  echo "Must supply path for merged files"
  exit 1
fi

target="$1"

deleted=""
if [ "$#" -gt 1 ]
then
  deleted="$2"
fi

target=${target%/}

for fld in NORM PAIR STEM GRFT
do
  mkdir -p "$target/$fld"
  find "$target/$fld" -name "*.mrg.gz" -delete
done

osname=`uname -s | sed -e 's/_NT-.*$/_NT/; s/^MINGW[0-9]*/CYGWIN/'`
if [ "$osname" = "CYGWIN_NT" -a -x /bin/cygpath ]
then
  target=`cygpath -w "$target"`
fi

target=${target%/}

for fld in NORM PAIR STEM GRFT
do
  echo "$fld"
  find "./$fld" -name "*.inv.gz" |
  sort |
  xargs -n 100 rchive -gzip -deleted "$deleted" -merge "$target" "$fld"
done
